"""schema ban dau

Revision ID: 516307d1f384
Revises:
Create Date: 2026-08-01 17:18:00.444131

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# TZDateTime là TypeDecorator riêng của dự án (luôn trả datetime aware UTC).
# Migration phải import đúng kiểu đó, không thay bằng sa.DateTime: chênh lệch
# giữa schema và model sẽ khiến autogenerate lần sau sinh diff giả.
import models

# revision identifiers, used by Alembic.
revision: str = "516307d1f384"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("at", models.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_entity", ["entity_type", "entity_id"], unique=False)

    op.create_table(
        "department",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("manager_email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "scan_result",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "address",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=False,
        ),
        sa.Column("address_int", sa.BigInteger(), nullable=False),
        sa.Column("alive", sa.Boolean(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column(
            "mac_address",
            sa.String(length=17).with_variant(postgresql.MACADDR(), "postgresql"),
            nullable=True,
        ),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("rtt_ms", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("scanned_at", models.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_result", schema=None) as batch_op:
        batch_op.create_index("ix_scan_addr_time", ["address_int", "scanned_at"], unique=False)

    op.create_table(
        "sync_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=64), nullable=True),
        sa.Column("started_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("items_seen", sa.Integer(), nullable=False),
        sa.Column("items_changed", sa.Integer(), nullable=False),
        sa.Column("findings_created", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "subnet",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cidr", sa.String(length=64), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "gateway",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=True,
        ),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("default_department_id", sa.String(length=36), nullable=True),
        sa.Column(
            "dhcp_range_start",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "dhcp_range_end",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reserved_ranges",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("allocation_policy", sa.String(length=32), nullable=False),
        sa.Column("cooldown_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_scan_ok_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("scan_staleness_hours", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_department_id"],
            ["department.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cidr"),
    )
    op.create_table(
        "device",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_code", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "device_type",
            sa.Enum(
                "vm",
                "physical_server",
                "workstation",
                "network_device",
                "appliance",
                name="devicetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("hypervisor_host", sa.String(length=255), nullable=True),
        sa.Column("vcenter_uuid", sa.String(length=64), nullable=True),
        sa.Column("os", sa.String(length=128), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("ram_gb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("disk_gb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "power_state",
            sa.Enum("on", "off", "suspended", "unknown", name="powerstate", native_enum=False),
            nullable=False,
        ),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("requester_email", sa.String(length=255), nullable=True),
        sa.Column("ticket_id", sa.String(length=32), nullable=True),
        sa.Column("provisioned_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "requested",
                "active",
                "expiring",
                "pending_reclaim",
                "shutdown",
                "archived",
                name="lifecyclestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "vcenter",
                "discovered",
                "imported",
                name="devicesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "criticality",
            sa.Enum("low", "normal", "critical", name="criticality", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("last_synced_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("created_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", models.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_code"),
        sa.UniqueConstraint("vcenter_uuid"),
    )
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.create_index("ix_device_dept", ["department_id"], unique=False)
        batch_op.create_index(
            "ix_device_lifecycle", ["lifecycle_status", "expires_at"], unique=False
        )

    op.create_table(
        "ip_address",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subnet_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=False,
        ),
        sa.Column("address_int", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "free",
                "reserved",
                "allocated",
                "quarantine",
                "blocked",
                "conflict",
                name="ipstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column(
            "mac_address",
            sa.String(length=17).with_variant(postgresql.MACADDR(), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_seen_alive_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("last_seen_dead_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("consecutive_dead_scans", sa.Integer(), nullable=False),
        sa.Column("consecutive_alive_scans", sa.Integer(), nullable=False),
        sa.Column("scans_last_7d", sa.Integer(), nullable=False),
        sa.Column("released_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("ever_assigned", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subnet_id"],
            ["subnet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", name="uq_ip_address"),
    )
    with op.batch_alter_table("ip_address", schema=None) as batch_op:
        batch_op.create_index("ix_ip_addr_int", ["address_int"], unique=False)
        batch_op.create_index("ix_ip_status_released", ["status", "released_at"], unique=False)
        batch_op.create_index("ix_ip_subnet_status", ["subnet_id", "status"], unique=False)

    op.create_table(
        "credential_ref",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("auth_type", sa.String(length=32), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("vault_path", sa.String(length=512), nullable=False),
        sa.Column("rotated_at", models.TZDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drift_finding",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "drift_type",
            sa.Enum(
                "ghost_vm",
                "unregistered_vm",
                "shadow_ip",
                "stale_allocation",
                "spec_mismatch",
                "missing_owner",
                "missing_expiry",
                "expired",
                "ip_conflict",
                name="drifttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open", "acknowledged", "resolved", "ignored", name="driftstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("subject_key", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("ip_address_id", sa.String(length=36), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", models.TZDateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ip_address_id"],
            ["ip_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drift_type", "subject_key", name="uq_drift_subject"),
    )
    with op.batch_alter_table("drift_finding", schema=None) as batch_op:
        batch_op.create_index("ix_drift_status_sev", ["status", "severity"], unique=False)

    op.create_table(
        "ip_assignment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ip_address_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("assigned_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("released_at", models.TZDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ip_address_id"],
            ["ip_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ip_assignment", schema=None) as batch_op:
        batch_op.create_index("ix_assignment_device", ["device_id"], unique=False)
        batch_op.create_index(
            "uq_active_ip_assignment",
            ["ip_address_id"],
            unique=True,
            postgresql_where=sa.text("released_at IS NULL"),
            sqlite_where=sa.text("released_at IS NULL"),
        )

    op.create_table(
        "ip_reservation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ip_address_id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.String(length=36), nullable=False),
        sa.Column("reserved_by", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=True),
        sa.Column("created_at", models.TZDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", models.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ip_address_id"],
            ["ip_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address_id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "lifecycle_event",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("at", models.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # --- Chỉ dành cho PostgreSQL ---
    # Index GiST trên INET là nền tảng của truy vấn IPAM theo dải
    # (`WHERE address <<= '10.0.76.0/24'`) — TECHNICAL-SPEC §10. SQLAlchemy
    # không diễn đạt được bằng kiểu portable nên phải viết SQL thô ở đây.
    #
    # Opclass `inet_ops` cho GiST đến từ extension btree_gist. Trên Postgres
    # có quyền superuser thì tạo được ngay; trên dịch vụ quản lý (Supabase,
    # RDS...) có thể bị từ chối hoặc extension nằm ở schema khác. Index này
    # là tối ưu hoá tốc độ, KHÔNG phải điều kiện đúng đắn — nên nếu tạo
    # không được thì cảnh báo rồi đi tiếp, thay vì làm hỏng cả lượt migrate.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    for table in ("ip_address", "scan_result"):
        name = "ix_ip_address_gist" if table == "ip_address" else "ix_scan_address_gist"
        op.create_index(
            name,
            table,
            ["address"],
            unique=False,
            postgresql_using="gist",
            postgresql_ops={"address": "inet_ops"},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_scan_address_gist", table_name="scan_result")
    op.drop_index("ix_ip_address_gist", table_name="ip_address")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lifecycle_event")
    op.drop_table("ip_reservation")
    with op.batch_alter_table("ip_assignment", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_ip_assignment",
            postgresql_where=sa.text("released_at IS NULL"),
            sqlite_where=sa.text("released_at IS NULL"),
        )
        batch_op.drop_index("ix_assignment_device")

    op.drop_table("ip_assignment")
    with op.batch_alter_table("drift_finding", schema=None) as batch_op:
        batch_op.drop_index("ix_drift_status_sev")

    op.drop_table("drift_finding")
    op.drop_table("credential_ref")
    with op.batch_alter_table("ip_address", schema=None) as batch_op:
        batch_op.drop_index("ix_ip_subnet_status")
        batch_op.drop_index("ix_ip_status_released")
        batch_op.drop_index("ix_ip_addr_int")

    op.drop_table("ip_address")
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.drop_index("ix_device_lifecycle")
        batch_op.drop_index("ix_device_dept")

    op.drop_table("device")
    op.drop_table("subnet")
    op.drop_table("project")
    op.drop_table("sync_run")
    with op.batch_alter_table("scan_result", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_addr_time")

    op.drop_table("scan_result")
    op.drop_table("department")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entity")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
